import type { Metadata } from "next";
import { roboto_condensed } from "./font";
import "./globals.css";
import Navigation from "./components/layout/Navigation";
import { UserProvider } from "./context/user.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        <UserProvider>
          <Navigation />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
