import type { Metadata } from "next";
import { roboto_condensed } from "./font";
import "./globals.css";
import Navigation from "./components/layout/navigation.component";
import { UserProvider } from "./context/user.context";
import { CategoriesProvider } from "./context/categories.context";
import { CartProvider } from "./context/cart.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        <UserProvider>
          <CategoriesProvider>
            <CartProvider>
            <Navigation />
            {children}
            </CartProvider>
          </CategoriesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
