import type { Metadata,Viewport } from "next";
import { roboto_condensed } from "./font";
import "./globals.css";
import Navigation from "../components/layout/navigation/navigation.component";
import Footer from "../components/layout/footer/footer.component";
import { UserProvider } from "../context/user.context";
import { CategoriesProvider } from "../context/categories.context";
import { CartProvider } from "../context/cart.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        <UserProvider>
          <CategoriesProvider>
            <CartProvider>
            <Navigation />
            <main>
              {children}
            </main>
            <Footer/>
            </CartProvider>
          </CategoriesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
